FROM node:24.2.0-bullseye-slim
WORKDIR /var/www/portfolio-project

COPY package*.json ./
RUN apt-get update && apt-get install -y git
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
