FROM node:23.10-alpine
WORKDIR /var/www/portfolio-project

COPY package*.json ./
RUN apk add --no-cache openssh-client git
RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts
RUN npm install

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]
