services:
  nextjs:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - ./app:/var/www/presentation-portfolio-project/app
      - /var/www/presentation-portfolio-project/node_modules
