services:
  nextjs:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    volumes:
      - ..:/var/www/presentation-portfolio-project
      - /var/www/presentation-portfolio-project/node_modules
